cicd: also push a versioned tag

diff --git a/.github/workflows/docker-publish.yml b/.github/workflows/docker-publish.yml
--- a/.github/workflows/docker-publish.yml
+++ b/.github/workflows/docker-publish.yml
@@ -15,6 +15,15 @@ jobs:
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
 
+      - name: Get syslog-ng version
+        id: get_version
+        run: |
+          version=$(grep -Eo 'syslog-ng [0-9]+\.[0-9]+\.[0-9]+' syslog-ng.conf | head -n1 | awk '{print $2}')
+          if [ -z "$version" ]; then
+            echo "Could not determine syslog-ng version from syslog-ng.conf"
+            exit 1
+          fi
+          echo "version=$version" >> $GITHUB_OUTPUT
       - name: Log in to GitHub Container Registry
         uses: docker/login-action@v3
         with:
@@ -28,4 +37,6 @@ jobs:
           context: .
           file: ./Dockerfile
           push: true
-          tags: ghcr.io/${{ github.repository }}:latest
+          tags: |
+            ghcr.io/${{ github.repository }}:latest
+            ghcr.io/${{ github.repository }}:${{ steps.get_version.outputs.version }}
